Vagrant.configure(2) do |config|
  config.vm.synced_folder File.expand_path("~/.dotfiles"), "/home/vagrant/.dotfiles", id: "v-dotfiles"
  config.vm.provision :shell, path: File.join(File.dirname(__FILE__), "scripts", "provision")

  # Otherwise the /vagrant folder will have the wrong permissions (on lxc, at least)
  if Process.uid != 1000

    # Use rsync because lxc doesn't support setting the uid and gid
    config.vm.synced_folder '.', '/vagrant', type: 'rsync', mount_options: ['uid=1000,gid=1000,bind']
  end
end
