alias docker-rm-all='sudo docker stop $(sudo docker ps -a -q); sudo docker rm $(sudo docker ps -a -q)'
alias docker-stop-all='sudo docker stop $(sudo docker ps -a -q)'
alias docker-prune='docker container prune -f; docker image prune -f'
alias dc='docker compose'
alias dcd='docker compose down'
alias dcu='docker compose up'
alias docker-compose='docker compose'
